export const HEROES = [
	{
		id: 'axe',
		nameKey: 'hero.axe.name',
		roleKey: 'role.offlane',
		roles: ['role.offlane', 'role.initiator'],
		winRate: '52.3%',
		pickRate: '17.8%',
		name: 'Axe',
		role: 'Hardlane',
		winrate: '53%',
		difficulty: 'Medium',
		attribute: 'Strength',
		strengths: ['hero.axe.strengths.initiation', 'hero.axe.strengths.sustain'],
		weaknesses: ['hero.axe.weaknesses.magic', 'hero.axe.weaknesses.push'],
		build: ['hero.axe.build.vanguard', 'hero.axe.build.bladeMail', 'hero.axe.build.blackKingBar'],
		items: ['item.bladeMail', 'item.arcaneBoots', 'item.blackKingBar', 'item.crimsonGuard'],
		skills: ['ability.berserkersCall', 'ability.counterHelix', 'ability.frenzy', 'ability.cullingBlade'],
		counters: ['hero.counter.drowRanger', 'hero.counter.phantomLancer', 'hero.counter.skywrathMage'],
		image: 'https://uk.dotabuff.com/assets/heroes/axe.jpg',
	},
	{
		id: 'invoker',
		nameKey: 'hero.invoker.name',
		roleKey: 'role.mid',
		roles: ['role.mid', 'role.caster'],
		winRate: '49.1%',
		pickRate: '21.4%',
		name: 'Invoker',
		role: 'Mid / Caster',
		winrate: '49.1%',
		difficulty: 'Hard',
		attribute: 'Intelligence',
		strengths: ['hero.invoker.strengths.flexibility', 'hero.invoker.strengths.teamfight'],
		weaknesses: ['hero.invoker.weaknesses.levelDependent', 'hero.invoker.weaknesses.controlled'],
		build: ['hero.invoker.build.travelBoots', 'hero.invoker.build.aghanim', 'hero.invoker.build.scotty'],
		items: ['item.travelBoots', 'item.aghanimsScepter', 'item.etherealBlade', 'item.scotty'],
		skills: ['ability.quas', 'ability.wex', 'ability.exort', 'ability.invoke'],
		counters: ['hero.counter.templarAssassin', 'hero.counter.puck', 'hero.counter.shadowFiend'],
		image: 'https://uk.dotabuff.com/assets/heroes/invoker.jpg',
	},
	{
		id: 'pudge',
		nameKey: 'hero.pudge.name',
		roleKey: 'role.roamer',
		roles: ['role.roamer', 'role.disabler'],
		winRate: '50.8%',
		pickRate: '15.2%',
		name: 'Pudge',
		role: 'Roamer',
		winrate: '51%',
		difficulty: 'Medium',
		attribute: 'Strength',
		strengths: ['hero.pudge.strengths.pickoffs', 'hero.pudge.strengths.mapPressure'],
		weaknesses: ['hero.pudge.weaknesses.cooldown', 'hero.pudge.weaknesses.ranged'],
		build: ['hero.pudge.build.rodOfAtos', 'hero.pudge.build.bladeMail', 'hero.pudge.build.blackKingBar'],
		items: ['item.rodOfAtos', 'item.bladeMail', 'item.blackKingBar', 'item.heart'],
		skills: ['ability.meatHook', 'ability.rot', 'ability.fleshHeap', 'ability.dismember'],
		counters: ['hero.counter.timberSaw', 'hero.counter.antiMage', 'hero.counter.windranger'],
		image: 'https://uk.dotabuff.com/assets/heroes/pudge.jpg',
	},
	// ... (rest of heroes copied from original Dota2Component)
];

// Note: This file intentionally uses a plain JS array to keep the data serializable and
// easy to import from both the Dota2 component and the guide component.
